project_name: Asterisk ARI Proxy
builds:
   - binary: ari-proxy
     env:
        - CGO_ENABLED=0
     goos:
        - windows
        - darwin
        - linux
     goarch:
        - amd64
        - arm64

archives:
   - id: ari-proxy
     format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
       - '^docs:'
       - '^test:'

dockers:
   - image_templates:
        - 'cycoresystems/ari-proxy:{{ .Tag }}-amd64'
        - 'cycoresystems/ari-proxy:v{{ .Major }}-amd64'
        - 'cycoresystems/ari-proxy:v{{ .Major }}.{{ .Minor }}-amd64'
        - 'cycoresystems/ari-proxy:latest-amd64'
     use: buildx
     dockerfile: Dockerfile.goreleaser
     build_flag_templates:
        - "--platform=linux/amd64"
   - image_templates:
        - 'cycoresystems/ari-proxy:{{ .Tag }}-arm64v8'
        - 'cycoresystems/ari-proxy:v{{ .Major }}-arm64v8'
        - 'cycoresystems/ari-proxy:v{{ .Major }}.{{ .Minor }}-arm64v8'
        - 'cycoresystems/ari-proxy:latest-arm64v8'
     use: buildx
     dockerfile: Dockerfile.goreleaser
     build_flag_templates:
        - "--platform=linux/arm64/v8"
docker_manifests:
  - name_template: 'cycoresystems/ari-proxy:{{ .Tag }}'
    image_templates:
      - cycoresystems/ari-proxy:{{ .Tag }}-amd64
      - cycoresystems/ari-proxy:{{ .Tag }}-arm64
  - name_template: 'cycoresystems/ari-proxy:{{ .Major }}'
    image_templates:
      - cycoresystems/ari-proxy:{{ .Major }}-amd64
      - cycoresystems/ari-proxy:{{ .Major }}-arm64
  - name_template: 'cycoresystems/ari-proxy:{{ .Major }}.{{ .Minor }}'
    image_templates:
      - cycoresystems/ari-proxy:{{ .Major }}.{{ .Minor }}-amd64
      - cycoresystems/ari-proxy:{{ .Major }}.{{ .Minor }}-arm64
  - name_template: 'cycoresystems/ari-proxy:latest'
    image_templates:
      - cycoresystems/ari-proxy:latest-amd64
      - cycoresystems/ari-proxy:latest-arm64
